# **Basics**

In [1]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [2]:
a = np.ones((2,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
a = np.zeros((1,5))
a

array([[0., 0., 0., 0., 0.]])

In [8]:
a = np.random.random(2) #only 1D array can be returned  
a 

array([0.12408245, 0.98810718])

In [6]:
a = np.random.rand(2,4) #2D or any dimensional array can be returned
a

array([[0.44780685, 0.40850126, 0.0808191 , 0.61394978],
       [0.25124396, 0.89998916, 0.84101901, 0.58941525]])

In [10]:
a = np.random.randn(2)  #returns n samples from standard normal fcuntion
a

array([ 2.1014549 , -0.70395368])

In [11]:
a = np.random.randint(5,10,4) #4 random integers from the interval 5 to 10
a

array([9, 7, 6, 8])

In [12]:
a = np.empty((2,4))
a

array([[0.44780685, 0.40850126, 0.0808191 , 0.61394978],
       [0.25124396, 0.89998916, 0.84101901, 0.58941525]])

In [15]:
a = np.full((2,3),55)  
a

array([[55, 55, 55],
       [55, 55, 55]])

In [17]:
a = np.arange(10,25,3)  #evenly spaced values in the interval 10 to 25 and increments 3
a

array([10, 13, 16, 19, 22])

In [19]:
a = np.linspace(2,10,3) # returns 3 evenly spaced values in interval 2 to 10 
a

array([ 2.,  6., 10.])

In [21]:
a = np.eye(4) #identity matrices are alwaus square matrices so one argument is enough
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
a = np.identity(7)
a

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [30]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


In [0]:
#when there are missing values and mixed data types always use genfromtxt. This is more lowlevel
my_array2 = np.genfromtxt('data2.txt',
                      skip_header=1,
                      filling_values=-999)  

In [0]:
#highlevel compared to genfromtext - cannot handle missing values.
x, y, z = np.loadtxt('data.txt',
                    skiprows=1,
                    unpack=True)

In [42]:
my_array = np.random.rand(5,5)
my_array
# Print the number of `my_array`'s dimensions #2d,3d or higher
print(my_array.ndim)

# Print the number of `my_array`'s elements  
print(my_array.size)

# Print information about `my_array`'s memory layout
print(my_array.flags)

# Print the length of one array element in bytes
print(my_array.itemsize)

# Print the total consumed bytes by `my_array`'s elements
print(my_array.nbytes)

# Print the length of `my_array`
print(len(my_array))

2
25
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

8
200
5


In [41]:
my_2d_array = np.random.rand(5,5)
print(my_2d_array)
# Print out memory address
print(my_2d_array.data)

# Print out the shape of `my_array`
print(my_2d_array.shape)

# Print out the data type of `my_array`
print(my_2d_array.dtype)

# Print out the stride of `my_array`  #(x,y) x bytes to find next row element, y bytes to find next column element
print(my_2d_array.strides)

[[0.29237692 0.28709041 0.85841937 0.17901566 0.98004985]
 [0.9167753  0.78949906 0.40455052 0.08866348 0.08977282]
 [0.01851982 0.71197056 0.13013526 0.83824676 0.72590998]
 [0.47014283 0.43340247 0.92452011 0.25755838 0.00653816]
 [0.96589055 0.32915828 0.01074092 0.23027823 0.19438176]]
(5, 5)
float64
(40, 8)


In [43]:
my_array.astype(float) #change the datatype of the array elements

array([[0.47802068, 0.33249647, 0.45273438, 0.08453316, 0.72098735],
       [0.68234637, 0.12677404, 0.48210018, 0.30277426, 0.37604092],
       [0.20522043, 0.95355041, 0.47901971, 0.59302008, 0.78554414],
       [0.65645637, 0.38337088, 0.86279203, 0.85281727, 0.4248223 ],
       [0.294185  , 0.65773827, 0.02679477, 0.59803414, 0.27051371]])

# **Elementwise Operations**

In [49]:
x =np.ones((3,4))
y = np.ones((1,4))
print(x, "\n")
print(y)

print("\n", x+y) #small array is added to the large array multiple times
#if they are of same size, simple elementwise additoin 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[1. 1. 1. 1.]]

 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [56]:
x = np.ones((3,4))
y = np.random.random((5,1,4))
print(x, "\n")
print(y)
#print("\n", x+y)
print("\n", np.add(x,y))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[[0.25267887 0.95034469 0.9289     0.65210894]]

 [[0.84617285 0.02592338 0.20447967 0.28491294]]

 [[0.94690886 0.95819356 0.47690925 0.41743548]]

 [[0.04065463 0.51419192 0.61180686 0.31187589]]

 [[0.30365299 0.12004477 0.63723557 0.73609648]]]

 [[[0.2419634  0.04965531 0.0711     0.34789106]
  [0.2419634  0.04965531 0.0711     0.34789106]
  [0.2419634  0.04965531 0.0711     0.34789106]]

 [[0.15382715 0.01491151 0.1820813  0.14526119]
  [0.15382715 0.01491151 0.1820813  0.14526119]
  [0.15382715 0.01491151 0.1820813  0.14526119]]

 [[0.05309114 0.04180644 0.04618149 0.16512904]
  [0.05309114 0.04180644 0.04618149 0.16512904]
  [0.05309114 0.04180644 0.04618149 0.16512904]]

 [[0.02428893 0.48580808 0.38819314 0.06437232]
  [0.02428893 0.48580808 0.38819314 0.06437232]
  [0.02428893 0.48580808 0.38819314 0.06437232]]

 [[0.08904103 0.03964181 0.36276443 0.26390352]
  [0.08904103 0.03964181 0.36276443 0.26390352]
  [0.08904103 0.0396

In [57]:
np.array_equal(x,y)

False